# Approach

We use cognitive modeling and neuroimaging to understand how people learn and make decisions. We are interested how these processes do, __or do not__ change as people get older. The ultimate goal of this research is to promote health and wellbeing across adulthood.

Recognize that this work is inherently interdisciplinary, meaning we will use tools and knowledge from traditional fields like psychology, neuroscience, and economics. Because it requires competency in so many different domains, the learning curve can be steep and it can feel overwhelming. But it is also inherently interesting, and rewarding work! 

## Mentorship and IDPs

To help you with this endeavor, you will be assigned a mentor within the lab. If you are a lab manager, graduate student, or postdoc, the Lab Director will likely be your mentor. If you are an undergraduate, you will likely be reporting to the lab manager, a graduate student, or a postdoc. To facilitate these relationships, we will use individual development plans (IDPs). The structure of IDPs will vary depending on your role in the lab, but generally they will set and track short-term and long-term goals. These will be created when you join the lab and be revisited each semester (i.e. Fall, Spring, and Summer).

## Feedback

You should expect to regularly receive feedback from your mentor and your peers. Feedback, especially negative feedback, can be discouraging and overwhelming. Please recognize that the purpose of feedback is to improve your work and help you meet your goals. Also know that giving critical and constructive feedback is an time-consuming effort and **try** to accept feedback in the spirit in which it is offered. As a group, we will discuss how to give and receive feedback.
