# Code of Conduct

## AWL Code of Conduct

All lab members are expected to agree with the following code of conduct. We will enforce this code as needed. We expect cooperation with all members to help ensure a safe environment for everyone. Please also see the [UT Dallas Nondiscrimination policy](https://policy.utdallas.edu/utdbp3090).

The Aging Well Lab is committed to providing a harrassment-free environment, regardless of gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, or religion (or lack thereof).  We do not tolerate harrassment of lab members in any form. Sexual language and imagery is generally not appropriate for any lab venue, including lab meetings, presentations, or discussions.

Harassment includes offensive verbal comments related to gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, religion, sexual images in public spaces, deliberate intimidation, stalking, following, harassing photography or recording, sustained disruption of talks or other events, inappropriate physical contact, and unwelcome sexual attention.

Members asked to stop any harassing behavior are expected to comply immediately.

If you are being harassed, notice that someone else is being harassed, or have any other concerns, please contact the lab director, Kendra Seaman immediately. If Dr. Seaman is the cause of your concern, then please reach out to one of the center director or another trusted center member who can assist.

We expect members to follow these guidelines at any lab-related event.

This section was adapted from the [MemoLab]( https://github.com/memobc/memolab-manual#code-of-conduct).

## Anonymous Lab Survey

Twice a year, we will conduct an anonymous lab culture survey. Because this survey is anonymous, you will be able to give honest feedback to the lab director about the culture of the lab. These surveys will be deployed near the end of the fall semester (first week of December) and spring semester (first week of May). 

## Contact Information

Dr. Kendra Seaman
AWL Director
kendra.seaman@utdallas.edu

Dr. Mick Rugg
CVL Director
mrugg@utdallas.edu

